name: Release

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - uses: actions/checkout@v4
        with: 
          # This token is scoped to public repo's and only has write contents_access
          # It is specifically required to allow commits back to this repository as part of `auto shipit`
          token: ${{ secrets.GH_PUBLIC_REPO_CONTENTS_ACCESS }}

      - name: Prepare repository
        # Fetch full git history and tags
        run: git fetch --unshallow --tags

      - name: Use NVM Node.js version
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          registry-url: 'https://npm.pkg.github.com'
          scope: "@amplience"

      - name: Create Release
        env:
          # environmental vars for actions/setup-node, should use same GH token for both GH_TOKEN and NPM_TOKEN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # this project is configured to use the auto-shipit/conventional-commits plugin
        run: |
          npm install --frozen-lockfile
          npm run build
          npx auto shipit
